package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "mmhbusin_lmstu")
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private Position position;
	private Role role;
	private String adminName;
	private String email;
	private String phone;
	private String address;
	private String address1;
	private String nrc;
	private Set<RentReturnTeacher> rentReturnTeachers = new HashSet<RentReturnTeacher>(0);
	private Set<RentReturnStudent> rentReturnStudents = new HashSet<RentReturnStudent>(0);

	public Admin() {
	}

	public Admin(Position position, Role role, String adminName, String email, String phone, String address,
			String nrc) {
		this.position = position;
		this.role = role;
		this.adminName = adminName;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.nrc = nrc;
	}

	public Admin(Position position, Role role, String adminName, String email, String phone, String address,
			String address1, String nrc, Set<RentReturnTeacher> rentReturnTeachers,
			Set<RentReturnStudent> rentReturnStudents) {
		this.position = position;
		this.role = role;
		this.adminName = adminName;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.address1 = address1;
		this.nrc = nrc;
		this.rentReturnTeachers = rentReturnTeachers;
		this.rentReturnStudents = rentReturnStudents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "admin_id", unique = true, nullable = false)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "position_id", nullable = false)
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "admin_name", nullable = false, length = 100)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false, length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "address1", length = 200)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "nrc", nullable = false, length = 100)
	public String getNrc() {
		return this.nrc;
	}

	public void setNrc(String nrc) {
		this.nrc = nrc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<RentReturnTeacher> getRentReturnTeachers() {
		return this.rentReturnTeachers;
	}

	public void setRentReturnTeachers(Set<RentReturnTeacher> rentReturnTeachers) {
		this.rentReturnTeachers = rentReturnTeachers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<RentReturnStudent> getRentReturnStudents() {
		return this.rentReturnStudents;
	}

	public void setRentReturnStudents(Set<RentReturnStudent> rentReturnStudents) {
		this.rentReturnStudents = rentReturnStudents;
	}

}
