package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "mmhbusin_lmstu")
public class Author implements java.io.Serializable {

	private Integer authorId;
	private String authorName;
	private Set<BookAuthor> bookAuthors = new HashSet<BookAuthor>(0);

	public Author() {
	}

	public Author(String authorName) {
		this.authorName = authorName;
	}

	public Author(String authorName, Set<BookAuthor> bookAuthors) {
		this.authorName = authorName;
		this.bookAuthors = bookAuthors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "author_id", unique = true, nullable = false)
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Column(name = "author_name", nullable = false, length = 100)
	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<BookAuthor> getBookAuthors() {
		return this.bookAuthors;
	}

	public void setBookAuthors(Set<BookAuthor> bookAuthors) {
		this.bookAuthors = bookAuthors;
	}

}
