package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookType generated by hbm2java
 */
@Entity
@Table(name = "book_type", catalog = "mmhbusin_lmstu")
public class BookType implements java.io.Serializable {

	private BookTypeId id;
	private Book book;
	private Type type;

	public BookType() {
	}

	public BookType(BookTypeId id, Book book, Type type) {
		this.id = id;
		this.book = book;
		this.type = type;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false)),
			@AttributeOverride(name = "typeId", column = @Column(name = "type_id", nullable = false)) })
	public BookTypeId getId() {
		return this.id;
	}

	public void setId(BookTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type_id", nullable = false, insertable = false, updatable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

}
