package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "mmhbusin_lmstu")
public class Book implements java.io.Serializable {

	private Integer bookId;
	private BookEdition bookEdition;
	private BookGroup bookGroup;
	private String bookName;
	private Date createDate;
	private int qty;
	private String isbn;
	private Date publisherDate;
	private Set<RentReturnTeacher> rentReturnTeachers = new HashSet<RentReturnTeacher>(0);
	private Set<BookType> bookTypes = new HashSet<BookType>(0);
	private Set<BookAuthor> bookAuthors = new HashSet<BookAuthor>(0);
	private Set<RentReturnStudent> rentReturnStudents = new HashSet<RentReturnStudent>(0);
	private Set<BookShell> bookShells = new HashSet<BookShell>(0);

	public Book() {
	}

	public Book(BookEdition bookEdition, BookGroup bookGroup, String bookName, Date createDate, int qty) {
		this.bookEdition = bookEdition;
		this.bookGroup = bookGroup;
		this.bookName = bookName;
		this.createDate = createDate;
		this.qty = qty;
	}

	public Book(BookEdition bookEdition, BookGroup bookGroup, String bookName, Date createDate, int qty, String isbn,
			Date publisherDate, Set<RentReturnTeacher> rentReturnTeachers, Set<BookType> bookTypes,
			Set<BookAuthor> bookAuthors, Set<RentReturnStudent> rentReturnStudents, Set<BookShell> bookShells) {
		this.bookEdition = bookEdition;
		this.bookGroup = bookGroup;
		this.bookName = bookName;
		this.createDate = createDate;
		this.qty = qty;
		this.isbn = isbn;
		this.publisherDate = publisherDate;
		this.rentReturnTeachers = rentReturnTeachers;
		this.bookTypes = bookTypes;
		this.bookAuthors = bookAuthors;
		this.rentReturnStudents = rentReturnStudents;
		this.bookShells = bookShells;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "book_id", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "edition_id", nullable = false)
	public BookEdition getBookEdition() {
		return this.bookEdition;
	}

	public void setBookEdition(BookEdition bookEdition) {
		this.bookEdition = bookEdition;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_group_id", nullable = false)
	public BookGroup getBookGroup() {
		return this.bookGroup;
	}

	public void setBookGroup(BookGroup bookGroup) {
		this.bookGroup = bookGroup;
	}

	@Column(name = "book_name", nullable = false, length = 100)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	@Column(name = "isbn", length = 100)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publisher_date", length = 10)
	public Date getPublisherDate() {
		return this.publisherDate;
	}

	public void setPublisherDate(Date publisherDate) {
		this.publisherDate = publisherDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<RentReturnTeacher> getRentReturnTeachers() {
		return this.rentReturnTeachers;
	}

	public void setRentReturnTeachers(Set<RentReturnTeacher> rentReturnTeachers) {
		this.rentReturnTeachers = rentReturnTeachers;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "book")
	public Set<BookType> getBookTypes() {
		return this.bookTypes;
	}

	public void setBookTypes(Set<BookType> bookTypes) {
		this.bookTypes = bookTypes;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "book")
	public Set<BookAuthor> getBookAuthors() {
		return this.bookAuthors;
	}

	public void setBookAuthors(Set<BookAuthor> bookAuthors) {
		this.bookAuthors = bookAuthors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<RentReturnStudent> getRentReturnStudents() {
		return this.rentReturnStudents;
	}

	public void setRentReturnStudents(Set<RentReturnStudent> rentReturnStudents) {
		this.rentReturnStudents = rentReturnStudents;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "book")
	public Set<BookShell> getBookShells() {
		return this.bookShells;
	}

	public void setBookShells(Set<BookShell> bookShells) {
		this.bookShells = bookShells;
	}

}
