package com.coder.model;
// Generated Sep 9, 2020 1:10:37 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookAvailable generated by hbm2java
 */
@Entity
@Table(name = "book_available", catalog = "mmhbusin_lmstu")
public class BookAvailable implements java.io.Serializable {

	private Integer id;
	private String userId;
	private int bookId;
	private Integer sent;

	public BookAvailable() {
	}

	public BookAvailable(String userId, int bookId) {
		this.userId = userId;
		this.bookId = bookId;
	}

	public BookAvailable(String userId, int bookId, Integer sent) {
		this.userId = userId;
		this.bookId = bookId;
		this.sent = sent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "book_id", nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "sent")
	public Integer getSent() {
		return this.sent;
	}

	public void setSent(Integer sent) {
		this.sent = sent;
	}

}
