package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookAuthorId generated by hbm2java
 */
@Embeddable
public class BookAuthorId implements java.io.Serializable {

	private int bookId;
	private int authorId;

	public BookAuthorId() {
	}

	public BookAuthorId(int bookId, int authorId) {
		this.bookId = bookId;
		this.authorId = authorId;
	}

	@Column(name = "book_id", nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "author_id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookAuthorId))
			return false;
		BookAuthorId castOther = (BookAuthorId) other;

		return (this.getBookId() == castOther.getBookId()) && (this.getAuthorId() == castOther.getAuthorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getAuthorId();
		return result;
	}

}
