package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookTypeId generated by hbm2java
 */
@Embeddable
public class BookTypeId implements java.io.Serializable {

	private int bookId;
	private int typeId;

	public BookTypeId() {
	}

	public BookTypeId(int bookId, int typeId) {
		this.bookId = bookId;
		this.typeId = typeId;
	}

	@Column(name = "book_id", nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "type_id", nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookTypeId))
			return false;
		BookTypeId castOther = (BookTypeId) other;

		return (this.getBookId() == castOther.getBookId()) && (this.getTypeId() == castOther.getTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getTypeId();
		return result;
	}

}
