package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookEdition generated by hbm2java
 */
@Entity
@Table(name = "book_edition", catalog = "mmhbusin_lmstu")
public class BookEdition implements java.io.Serializable {

	private Integer editionId;
	private String editionName;
	private Set<Book> books = new HashSet<Book>(0);

	public BookEdition() {
	}

	public BookEdition(String editionName) {
		this.editionName = editionName;
	}

	public BookEdition(String editionName, Set<Book> books) {
		this.editionName = editionName;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "edition_id", unique = true, nullable = false)
	public Integer getEditionId() {
		return this.editionId;
	}

	public void setEditionId(Integer editionId) {
		this.editionId = editionId;
	}

	@Column(name = "edition_name", nullable = false, length = 100)
	public String getEditionName() {
		return this.editionName;
	}

	public void setEditionName(String editionName) {
		this.editionName = editionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookEdition")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
