package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gread generated by hbm2java
 */
@Entity
@Table(name = "gread", catalog = "mmhbusin_lmstu")
public class Gread implements java.io.Serializable {

	private Integer greadId;
	private String greadName;
	private String greadNo;
	private Set<Student> students = new HashSet<Student>(0);

	public Gread() {
	}

	public Gread(String greadName, String greadNo) {
		this.greadName = greadName;
		this.greadNo = greadNo;
	}

	public Gread(String greadName, String greadNo, Set<Student> students) {
		this.greadName = greadName;
		this.greadNo = greadNo;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "gread_id", unique = true, nullable = false)
	public Integer getGreadId() {
		return this.greadId;
	}

	public void setGreadId(Integer greadId) {
		this.greadId = greadId;
	}

	@Column(name = "gread_name", nullable = false, length = 50)
	public String getGreadName() {
		return this.greadName;
	}

	public void setGreadName(String greadName) {
		this.greadName = greadName;
	}

	@Column(name = "gread_no", nullable = false, length = 30)
	public String getGreadNo() {
		return this.greadNo;
	}

	public void setGreadNo(String greadNo) {
		this.greadNo = greadNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gread")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
