package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major", catalog = "mmhbusin_lmstu")
public class Major implements java.io.Serializable {

	private Integer majorId;
	private String majorName;
	private String shortTerm;
	private Set<Student> students = new HashSet<Student>(0);

	public Major() {
	}

	public Major(String majorName, String shortTerm) {
		this.majorName = majorName;
		this.shortTerm = shortTerm;
	}

	public Major(String majorName, String shortTerm, Set<Student> students) {
		this.majorName = majorName;
		this.shortTerm = shortTerm;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "major_id", unique = true, nullable = false)
	public Integer getMajorId() {
		return this.majorId;
	}

	public void setMajorId(Integer majorId) {
		this.majorId = majorId;
	}

	@Column(name = "major_name", nullable = false, length = 100)
	public String getMajorName() {
		return this.majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	@Column(name = "short_term", nullable = false, length = 50)
	public String getShortTerm() {
		return this.shortTerm;
	}

	public void setShortTerm(String shortTerm) {
		this.shortTerm = shortTerm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "major")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
