package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RentReturnTeacher generated by hbm2java
 */
@Entity
@Table(name = "rent_return_teacher", catalog = "mmhbusin_lmstu")
public class RentReturnTeacher implements java.io.Serializable {

	private Integer teaRentId;
	private Admin admin;
	private Book book;
	private Teacher teacher;
	private Date rentDate;
	private Date returnDate;
	private Date dueDate;
	private int lateFeet;
	private int sent;

	public RentReturnTeacher() {
	}

	public RentReturnTeacher(Admin admin, Book book, Teacher teacher, Date rentDate, Date returnDate, Date dueDate,
			int lateFeet,int sent) {
		this.admin = admin;
		this.book = book;
		this.teacher = teacher;
		this.rentDate = rentDate;
		this.returnDate = returnDate;
		this.dueDate = dueDate;
		this.lateFeet = lateFeet;
		this.sent=sent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tea_rent_id", unique = true, nullable = false)
	public Integer getTeaRentId() {
		return this.teaRentId;
	}

	public void setTeaRentId(Integer teaRentId) {
		this.teaRentId = teaRentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "admin_id", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "teacher_id", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rent_date", nullable = false, length = 10)
	public Date getRentDate() {
		return this.rentDate;
	}

	public void setRentDate(Date rentDate) {
		this.rentDate = rentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "return_date", nullable = false, length = 10)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", nullable = false, length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "late_feet", nullable = false)
	public int getLateFeet() {
		return this.lateFeet;
	}

	public void setLateFeet(int lateFeet) {
		this.lateFeet = lateFeet;
	}
	@Column(name = "sent", nullable = true)
	public int getSent() {
		return this.sent;
	}

	public void setSent(int sent) {
		this.sent = sent;
	}

}
