package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RentReturnStudent generated by hbm2java
 */
@Entity
@Table(name = "rent_return_student", catalog = "mmhbusin_lmstu")
public class RentReturnStudent implements java.io.Serializable {

	private Integer stuRentId;
	private Admin admin;
	private Book book;
	private Student student;
	private Date rentDate;
	private Date returnDate;
	private Date dueDate;
	private int lateFeet;
	private String sent;

	public RentReturnStudent() {
	}

	public RentReturnStudent(Admin admin, Book book, Student student, Date rentDate, Date returnDate, Date dueDate,
			int lateFeet,String sent) {
		this.admin = admin;
		this.book = book;
		this.student = student;
		this.rentDate = rentDate;
		this.returnDate = returnDate;
		this.dueDate = dueDate;
		this.lateFeet = lateFeet;
		this.sent=sent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stu_rent_id", unique = true, nullable = false)
	public Integer getStuRentId() {
		return this.stuRentId;
	}

	public void setStuRentId(Integer stuRentId) {
		this.stuRentId = stuRentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "admin_id", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rent_date", nullable = false, length = 10)
	public Date getRentDate() {
		return this.rentDate;
	}

	public void setRentDate(Date rentDate) {
		this.rentDate = rentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "return_date", nullable = true, length = 10)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", nullable = false, length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "late_feet", nullable =true)
	public int getLateFeet() {
		return this.lateFeet;
	}

	public void setLateFeet(int lateFeet) {
		this.lateFeet = lateFeet;
	}
	@Column(name = "sent", nullable =true, length = 20)
	public String getSent() {
		return this.sent;
	}

	public void setSent(String sent) {
		this.sent = sent;
	}


}
