package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shell generated by hbm2java
 */
@Entity
@Table(name = "shell", catalog = "mmhbusin_lmstu")
public class Shell implements java.io.Serializable {

	private Integer shellId;
	private String shellNo;
	private Set<BookShell> bookShells = new HashSet<BookShell>(0);

	public Shell() {
	}

	public Shell(String shellNo) {
		this.shellNo = shellNo;
	}

	public Shell(String shellNo, Set<BookShell> bookShells) {
		this.shellNo = shellNo;
		this.bookShells = bookShells;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shell_id", unique = true, nullable = false)
	public Integer getShellId() {
		return this.shellId;
	}

	public void setShellId(Integer shellId) {
		this.shellId = shellId;
	}

	@Column(name = "shell_no", nullable = false, length = 70)
	public String getShellNo() {
		return this.shellNo;
	}

	public void setShellNo(String shellNo) {
		this.shellNo = shellNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shell")
	public Set<BookShell> getBookShells() {
		return this.bookShells;
	}

	public void setBookShells(Set<BookShell> bookShells) {
		this.bookShells = bookShells;
	}

}
