package com.coder.model;
// Generated Aug 10, 2020 11:24:30 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "mmhbusin_lmstu")
public class Student implements java.io.Serializable {

	private Integer studentId;
	private AcademicYear academicYear;
	private Gread gread;
	private Major major;
	private Member member;
	private int rollNumber;
	private String studentName;
	private String gender;
	private String phone;
	private Date createDate;
	private String email;
	private String address;
	private String address1;
	private Set<RentReturnStudent> rentReturnStudents = new HashSet<RentReturnStudent>(0);

	public Student() {
	}

	public Student(AcademicYear academicYear, Gread gread, Major major, Member member, int rollNumber,
			String studentName, String gender, String phone, Date createDate, String email, String address) {
		this.academicYear = academicYear;
		this.gread = gread;
		this.major = major;
		this.member = member;
		this.rollNumber = rollNumber;
		this.studentName = studentName;
		this.gender = gender;
		this.phone = phone;
		this.createDate = createDate;
		this.email = email;
		this.address = address;
	}

	public Student(AcademicYear academicYear, Gread gread, Major major, Member member, int rollNumber,
			String studentName, String gender, String phone, Date createDate, String email, String address,
			String address1, Set<RentReturnStudent> rentReturnStudents) {
		this.academicYear = academicYear;
		this.gread = gread;
		this.major = major;
		this.member = member;
		this.rollNumber = rollNumber;
		this.studentName = studentName;
		this.gender = gender;
		this.phone = phone;
		this.createDate = createDate;
		this.email = email;
		this.address = address;
		this.address1 = address1;
		this.rentReturnStudents = rentReturnStudents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "year_id", nullable = false)
	public AcademicYear getAcademicYear() {
		return this.academicYear;
	}

	public void setAcademicYear(AcademicYear academicYear) {
		this.academicYear = academicYear;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gread_id", nullable = false)
	public Gread getGread() {
		return this.gread;
	}

	public void setGread(Gread gread) {
		this.gread = gread;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "major_id", nullable = false)
	public Major getMajor() {
		return this.major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "roll_number", nullable = false)
	public int getRollNumber() {
		return this.rollNumber;
	}

	public void setRollNumber(int rollNumber) {
		this.rollNumber = rollNumber;
	}

	@Column(name = "student_name", nullable = false, length = 100)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "gender", nullable = false, length = 50)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", nullable = false, length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "address1", length = 200)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "student")
	public Set<RentReturnStudent> getRentReturnStudents() {
		return this.rentReturnStudents;
	}

	public void setRentReturnStudents(Set<RentReturnStudent> rentReturnStudents) {
		this.rentReturnStudents = rentReturnStudents;
	}

}
