package com.coder.model;
// Generated Dec 2, 2020 10:17:26 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestCode generated by hbm2java
 */
@Entity
@Table(name = "test_code", catalog = "mmhbusin_lmstu")
public class TestCode implements java.io.Serializable {

	private Integer codeId;
	private String code;
	private String status;
	private String mail;

	public TestCode() {
	}

	public TestCode(String code, String status,String mail) {
		this.code = code;
		this.status = status;
		this.mail=mail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code_id", unique = true, nullable = false)
	public Integer getCodeId() {
		return this.codeId;
	}

	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}

	@Column(name = "code", nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status", nullable = false, length = 30)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@Column(name = "mail", nullable = false, length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
