package com.coder.model;
// Generated May 28, 2020 10:14:49 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "mmhbusin_lmstu")
public class Type implements java.io.Serializable {

	private Integer typeId;
	private BookGroup bookGroup;
	private String typeName;
	private String typeCode;
	private Set<BookType> bookTypes = new HashSet<BookType>(0);

	public Type() {
	}

	public Type(BookGroup bookGroup, String typeName, String typeCode) {
		this.bookGroup = bookGroup;
		this.typeName = typeName;
		this.typeCode = typeCode;
	}

	public Type(BookGroup bookGroup, String typeName, String typeCode, Set<BookType> bookTypes) {
		this.bookGroup = bookGroup;
		this.typeName = typeName;
		this.typeCode = typeCode;
		this.bookTypes = bookTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "type_id", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_group_id", nullable = false)
	public BookGroup getBookGroup() {
		return this.bookGroup;
	}

	public void setBookGroup(BookGroup bookGroup) {
		this.bookGroup = bookGroup;
	}

	@Column(name = "type_name", nullable = false, length = 100)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "type_code", nullable = false, length = 100)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy = "type")
	public Set<BookType> getBookTypes() {
		return this.bookTypes;
	}

	public void setBookTypes(Set<BookType> bookTypes) {
		this.bookTypes = bookTypes;
	}

}
